### ISSUE TITLE
ScanManifest output uses mixed absolutePath / relativePath across graphs + components

### ISSUE THREAD

**Issue by brphelps** [microsoft/component-detection#124]
👋 A coworker on the dependency-graph team at GitHub has been integrating component-detection into a lightweight action to use an API we are preparing to take to open beta. As part of this work, we're using both the `componentsFound` and `dependencyGraphs` fields: we're starting from a found component and then looking up dependency relationships in the graph.

One hurdle that exists today is that there is mixed absolute/relative pathing across these two collections. That is, if I take a given found component: 
<img width="968" alt="image" src="https://user-images.githubusercontent.com/10023676/173118542-24334c46-24a0-4ef9-8d2e-a68074a38e00.png">

it has a "locations found at" that is _almost_ usable to get the graph from the dependency graphs collection. However, these paths can be relative (I believe they can _also_ be absolute), and trying to compare that to a dependency graph (which is absolute) is non trivial. 

<img width="968" alt="image" src="https://user-images.githubusercontent.com/10023676/173118989-c8902b43-21b0-4c08-b6bb-d6c4f1828a73.png">

The main reason the comparison is "hard" is because the dependency graphs collection is using "always absolute" paths in its dictionary. This isn't really a problem in and of itself, but we don't have a way to easily infer the absolute path from the `foundComponent` perspective. If `foundComponent` had the absolute path as a property, that would be the easiest solution for manifest consumers (and maybe the most consistent overall for the output).

One lighter touch mitigation I was thinking of was just including the "parent" to the relative directories in the scan manifest output. While this is part of the input to component detection, I'm guessing we should be able to completely reason about the scan manifest output w/o having advance knowledge of the input.

**Comment by cobya** [comment]
We decided to go with the lightweight approach here of adding the `SourceDirectory` field in the outputted ScanResult and ScanManifest file so consumers can quickly find absolute paths.

While the normalized approach was initially considered, dependent tooling would have hit a few issues resolving the new paths. In addition, a second approach of adding the absolute path as part of the `componentsFound` array was considered but this resulted in a large increase in output size due to the additional text. For usability, this was not an optimal solution so the lightweight approach was chosen.
