### ISSUE TITLE
Should ignore comment in go.mod

### ISSUE THREAD

**Issue by karataliu** [microsoft/component-detection#645]
go.mod
```
require (
  // abc
)
```

will result in 
```
--- Component: ---
// abc - Go
--- Found at: ---
```

**Comment by cobya** [comment]
Is this happening when using the Go CLI scanning method, go.mod / go.sum parsing, or both? See https://github.com/microsoft/component-detection/blob/main/docs/detectors/go.md for more info

**Comment by karataliu** [comment]
Both `Default Detection strategy` and `Fallback Detection strategy` have the issue

**Comment by jcfiorenzano** [comment]
Tested the issue and this is only happening when we use the fallback strategy. @karataliu I think that in your case you saw the issue with the CLI detector because your `go.mod` is missing the module definition. For example, a correct go.mod file will look like:

```
module github.com/jcf/test
go 1.22.1

require (
	// abc
)
```
This `go.mod` file will be scanned by the CLI detector and no component will be found

![Image](https://github.com/microsoft/component-detection/assets/5582507/5fbdac5c-7959-4900-b416-53602e706da6)

However, if we use something like

```
require (
      // abc
)
```

then the CLI detector won't be executed as the file is missing the module definition

```
Go CLI command "go list -m -json all" failed with error: go: error reading go.mod: missing module declaration. To specify the module path:
        go mod edit -module=example.com/mod
```

In such case our in-house parser (the fallback strategy) will take place and then the fake component will be detected



![Image](https://github.com/microsoft/component-detection/assets/5582507/4400f09e-55a8-4019-bb8a-0f65c7a25164)
